name: Fantasy
version: 0.1
author: the_waltster
main: me.waltster.Fantasy.FantasyMain
commands:
  help:
    description: Get help!
  die:
    description: Restart your game
  class:
    description: Select your class or open the class selector
  race:
    description: Select your race or open race selector
